# Notebook 1: Basic Example

Here we will introduce a basic example of how **BATTLESIMULATOR** works and can be of benefit to you.

### Requirements:

- `numpy`
- `pandas`
- `matplotlib`
- `scipy.stats`
- `numba`

In [1]:
import sys
# map path back to the directory above battlesim/
sys.path.insert(0,"../")
# our main import
import battlesim as bsm

### Other Imports

In [2]:
from IPython.display import HTML
%matplotlib inline

## Create a Battle using the CloneWars Dataset

In [3]:
battle = bsm.Battle("../datasets/starwars-clonewars.csv")
battle

bsm.Battle(init=False)

### Within the `db_` object, we can see the table of information

This table represents the *knowledge* or statistics of each unit. These can be your own values/unit names, but the following column names **MUST** be present and the same within your own file, ideally in `.csv` file format.

In [4]:
battle.db_

Allegiance        Type  Armor   HP  Damage  \
Name                                                                  
local militia              Republic    Standard     15   20      10   
b1 battledroid                  CIS    Standard     40   20      15   
clone trooper              Republic    Standard     45   35      16   
b2 battledroid                  CIS    Standard    100   40      20   
arc trooper                Republic       Elite    100  100      20   
bx-series droid commando        CIS       Elite     70   50      22   
clone sharpshooter         Republic  Specialist     50   40      50   
battle droid assassin           CIS  Specialist     60   20      50   
clone commando             Republic       Elite    100  120      20   
t-series tactical droid         CIS       Elite    200   50      22   
magmaguard                      CIS       Elite    400  150     200   

                          Dmg Speed  Range  Movement Speed  Accuracy  Miss  \
Name                                                                         
local militia                  1.00    2.0             0.6         5    30   
b1 battledroid                 1.00    2.5             0.5        30    35   
clone trooper                  1.20    3.0             0.7        65    65   
b2 battledroid                 1.20    3.5             0.4        70    40   
arc trooper                    0.90    5.0             1.0        90    95   
bx-series droid commando       1.30    7.0             0.8        70    95   
clone sharpshooter             0.20   15.0             0.2        60    40   
battle droid assassin          0.15   15.0             0.2        55    45   
clone commando                 1.50    3.0             0.9        97    97   
t-series tactical droid        1.50    3.0             0.7        95    90   
magmaguard                     0.15    0.4             0.4       100    40   

                          Shield  Shield Regen  allegiance_int  
Name                                                            
local militia                  0          0.00               0  
b1 battledroid                 0          0.00               1  
clone trooper                  0          0.00               0  
b2 battledroid                 0          0.00               1  
arc trooper                    0          0.00               0  
bx-series droid commando       0          0.00               1  
clone sharpshooter             0          0.00               0  
battle droid assassin          0          0.00               1  
clone commando                30          0.20               0  
t-series tactical droid      100          0.18               1  
magmaguard                     0           NaN               1

    mutable_vars = ["x", "y", 'Armor', "HP", "Range", "Shield"]
    immutable_vars = ["Damage", "Dmg Speed", "Movement Speed", "Accuracy", "Miss", "Shield Regen", "Allegiance", "Type"]

## Initialise

The other elements within `battle` are not initialized yet, we need to *declare groups of units* using the names on the columns above, followed by the number of that unit we wish to use.

More than one **army** can be created in a function call. *Case is ignored*.

`create_army()` returns the `Battle` object to allow for function-chaining.

Multiple calls to `create_army()` override the previous calls, so armies are not *stacked*.

In [5]:
battle.create_army([("b1 battledroid", 10), ("clone trooper", 5)])

bsm.Battle(init=True, n_armies=2, simulated=False)

### We can view the armies we have stored:

In [6]:
battle.army_set_

(('b1 battledroid', 10), ('clone trooper', 5))

In [7]:
battle.S_[battle.S_['id']==1]['speed']

array([0.7], dtype=float32)

In [8]:
battle.M_[battle.M_['id'] == 0]['hp'] + battle.S_[battle.S_['id']==0]['speed']

array([20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5],
      dtype=float32)

### We can view the composition:

You notice that we have some interesting columns that detail what each 'army' is doing:

1. *position*: this defines how to spawn the unit, i.e with a normal distribution
2. *init_ai*: this defines how the army will find the nearest enemy at the start
3. *rolling_ai*: this defines how the army will find the nearest enemy throughout simulation progression
4. *decision_ai*: a broad suite of AI algorithms that define how the 'army' behaves. by default they act aggressively by chasing the enemy.

In [9]:
battle.composition_

unit allegiance   n         position  init_ai rolling_ai  \
0  b1 battledroid        CIS  10  norm (0.0, 0.0)  nearest    nearest   
1   clone trooper   Republic   5  norm (2.0, 2.0)  nearest    nearest   

  decision_ai  
0  aggressive  
1  aggressive

### Internally, a matrix `M` is created:

Here the *M* stands for mutability.

This enables efficiency when we call simulation functions, to have it within **numpy arrays**.

We can specifically view the columns available by checking the custom dtype:

In [10]:
battle.M_

array([(0, 0,  0.33497703,  1.2714309 , 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0, -0.98912764, -0.17186537, 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0, -0.9158731 , -0.73771995, 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0,  1.5699708 , -0.13416363, 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0, -0.9988333 ,  2.5834782 , 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0,  0.85170835, -2.2048523 , 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0, -1.4687183 ,  0.9730145 , 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0, -0.07147288,  0.18339026, 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0,  0.31420445,  2.0974405 , 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (0, 0,  0.46670845, -0.38236445, 20., 40., 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (1, 0,  1.9280778 ,  1.7862633 , 35., 45., 16., 3. , 0.7, 0.65, 0.65, 0, 2, 0),
       (1, 0,  2.2421486 ,  2.8067296 , 35.

### Considering static information

In addition to dynamically changing variables, we also need to reference unchanging data such as base damage, base speed and so on. This is held within the `S_` matrix:

In [11]:
battle.S_

array([(0, 15., 2.5, 0.5, 0.3 , 0.35, 0, 1, 1),
       (1, 16., 3. , 0.7, 0.65, 0.65, 0, 2, 0)],
      dtype={'names':['id','dmg','range','speed','acc','dodge','group','utype','team'], 'formats':['<u4','<f4','<f4','<f4','<f4','<f4','u1','u1','u1'], 'offsets':[0,4,8,12,16,20,24,25,26], 'itemsize':28, 'aligned':True})

## Changing Attributes

Right now, despite the fact that we have two *army groups* who will attack each other, they currently sit on top of each other as they are randomly distributed around $(0, 0)$. 

To change this, we need to *apply positioning* to each army group. There are several ways to do this:

1. Create `Distribution` objects for each army group. A Distribution is based on a statistical distribution such as normal, uniform or other, with given parameters.
2. Define distributions using the parameters found in certain `scipy.stats.*` distributions.
3. Use a premade *distribution function* within the `Battle` object and simply pass the statistical parameters desired. Note that these functions are **deprecated**.

Multiple calls to `apply_position_*` will **override** previous calls.

I personally prefer passing dictionaries for each army group, giving the name/id/dist name, with associated parameters. You can also specify to separate $x$ and $y$ parameters using `x_` or `y_` as prefixes to the parameter you wish to adjust. These can be suffixes instead.

In [12]:
battle.apply_position([
    dict(name="gaussian", x_loc=0, y_loc=0, scale=1),
    dict(name="gaussian", x_loc=10, y_loc=5, scale=1)
])

bsm.Battle(init=True, n_armies=2, simulated=False)

Note that `battle.apply_position_gaussian` and `battle.apply_position_uniform` have deprecated and no longer in development.

### Changing AI behaviour

By default, every army group will initialise by choosing a random enemy. Once that enemy is dead, it will then randomly select a new enemy and move towards it.

This can be altered using a number of AI functions, these include:

- `random`: selects a random enemy.
- `nearest`: selects the closest enemy.
- `pack`: selects the most common enemy among your closest allies.
- `weakest`: selects the enemy with the lowest HP.
- `strongest`: selects the enemy with the highest HP.

This can be chosen at the initial stage before the simulation starts (`init_ai`) or during the running of the simulation (`rolling_ai`).

Each element in the list corresponds to that army groups AI programming. It effects every unit within that army group.

In [13]:
battle.set_initial_ai(["random", "nearest"])

bsm.Battle(init=True, n_armies=2, simulated=False)

In [14]:
battle.set_rolling_ai(["nearest", "close_weak"])

bsm.Battle(init=True, n_armies=2, simulated=False)

#### Checking the composition again...

We see that the AIs have changed.

In [15]:
battle.composition_

unit allegiance   n          position  init_ai  rolling_ai  \
0  b1 battledroid        CIS  10   norm (0.0, 0.0)   random     nearest   
1   clone trooper   Republic   5  norm (10.0, 5.0)  nearest  close_weak   

  decision_ai  
0  aggressive  
1  aggressive

## Running the Simulation

Simulations are run individually using the `simulate()` function. This function by default requires no parameters, but you can send some if you wish to influence some global attribute regarding the simulation.

Simulations can be called directly using the `M_` attribute and functions within the `simulator.py` file, such as `simulate_battle`.

By default, the `simulate()` function returns a `pandas.DataFrame` object which details the change of units over time. This should be stored in some object. **WARNING**: Large numbers of units within the simulation may cause this function to run slowly.

In addition, the `battle` object also stores an attribute called `sim_` which is the same as the object returned from the `simulate()` function, if you wish to refer to it later.

In [16]:
S = battle.simulate()

### The Results

The resulting object always contains *at least* the following columns:

- `army`: Which army the unit belongs to
- `allegiance`: Which team the unit belongs to
- `alive`: A boolean flag that indicates whether this unit is alive
- `x`, `y`: X-Y coordinates
- `dir_x`, `dir_y`: The direction the unit is pointing from $(0, 0)$ origin.

In [24]:
S[0]['utype']

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2], dtype=uint8)

In [18]:
#S.head()

## Visualization

One of the principle aims of this project was to actively visualise the simulation in 2D space over time. To do this, we provide a number of simulation plotting functions which you can directly use with ease. The easiest way to do this, within a *Jupyter Notebook*, is to call the convenience function `sim_jupyter()`. This function uses the cached `sim_` object (i.e the last fight simulated) and draws the variables using the data stored in the `db_` object.

In [19]:
import matplotlib.pyplot as plt
# you may need to set the automatic animation.writer to ffmpeg, ensure ffmpeg is installed
plt.rcParams['animation.writer'] = 'ffmpeg'

In [20]:
battle.sim_jupyter()

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

### Generating HTML

The returned object from this function is from `matplotlib.animation.FuncAnimation`, an animation object. It contains a crucial function that converts this data into HTML/Javascript such that it can be displayed in Jupyter Notebook, called `to_jshtml()`.

In [ ]:
html = battle.sim_jupyter(create_html=True)

In [ ]:
html[:200]

### Displaying the HTML

IPython display then provides us with a `HTML()` function which converts HTML code text into HTML output.

Widgets at the bottom provide interaction to play, pause, rewind etc.

### Explaining the GUI

Notice that every **unit** is represented as an arrow, with the colours assigned to each **allegiance**, when a unit dies it becomes a static cross (`x`). The arrows move towards each other until in range, then attack, if they have the *aggressive* decision AI stance. The **size** of the arrow determines how powerful/important each unit type is.

Note that by default, the correct allegiance labels are passed to each group if you use `sim_jupyter` as a function from the `Battle` object. However you can also pass manual colours for each group if you don't like the defaults.

In [ ]:
HTML(html)

### Extra Display Options

You may notice that random colours and labels have been assigned to **each army group**. This is because the meta-information from our `battle` object which contain labels like `[CIS, Republic]` are not passed to the drawing function. These have to be manually passed within our `quiver_fight()` function.

The function accepts a dictionary where the index is a number, referring to the army group, and the value is the text/color to display:

There's the end of this first basic introduction to **BATTLESIMULATOR**.